deployment:
  replicas: 5
  imageVersion: trixie
service:
  type: NodePort
  servicePort: 80

deployment2:
 name: mongodb
 replicas: 1
 imageVersion: v1
port:
 containerPort: 27017
 
service2:
 port: 27017
 